### ISSUE TITLE
[bug] MOBILE - User profile settings 

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#842] opened 2019-12-28 08:16 UTC
**Describe the bug**
When I change focus of my profile (for example: from member to workspace, but any combination applies) I am asked to confirm because my profile will be reset. If I select "Cancel" (to not change) the new focus I've just selected stays selected and looks like has been changed anyways.

**Comment by tudi2d** [comment] 2020-02-18 16:25
I would like to investigate & fix this issue.

**Comment by chrismclarke** [comment] 2020-02-19 07:20
Sounds good, there's likely a few moving parts causing the issue (form and store), if you can figure it out just make a PR to master with reference to the issue. Thanks!

**Comment by tudi2d** [comment] 2020-02-21 12:04
*Workflow:*
- Go to profile
- Changed Profile (e.g. "Focus")
- Navigate to other page (e.g. "Map")
- Cancel confirmation dialog

I´ve tested this with Firefox on Android & Windows for the live & dev version and I was not able to reproduce the error. @sovesove can you please verify I´ve my steps are right? Maybe this issue was already fixed in a different commit during the last 2 months.

![4Y9OmGgmFU](https://user-images.githubusercontent.com/8904624/75032829-cafce900-54a9-11ea-89bd-0d2ded284a7f.gif)

**Closed** 2020-04-19 03:53 UTC
Labels: Priority: High❕, Type:Bug🐛
