### ISSUE TITLE
[mobile] Inconsistent space btw how-tos 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1850] opened 2022-07-24 15:45 UTC
Issue:
In the how-tos in the list page have inconsistent spacing. 

Link:
https://community.preciousplastic.com/how-to

Screenshots:
![Screenshot_20220724-173808_Brave](https://user-images.githubusercontent.com/17761877/180655126-74761c7c-023f-4626-b7fc-11b326032e03.png)

Proposal:
All how-tos have equal spacing btw them (30px).

**Comment by asheerrizvi** [comment] 2022-07-26 08:31
I can take this up.

**Comment by thisismattia** [comment] 2022-07-27 06:29
Nice one @asheerrizvi let me know if you need any help/support on that

**Comment by asheerrizvi** [comment] 2022-07-30 09:49
Since these cards can be of different heights (depending on the text in each of them), can we have masonic layout for this?

@thisismattia what do you think?

**Comment by asheerrizvi** [comment] 2022-07-30 09:52
It seems like these cards can have different heights based on their text. Should I go for a grid based solution (will result in extra space where the adjacent cards aren't equal in height), or we can go for a masonic layout?

@thisismattia

**Comment by thisismattia** [comment] 2022-07-30 10:07
hey @asheerrizvi thanks for following up on this. If I understand it correctly, masonic layout is what we're after. 

This would be ideal layout on desktop which I would assume cascading trough mobile. Let me know if that is what you meant or if I am getting it completely wrong  😇
<img width="1346" alt="Screenshot_2022-07-30_at_12_05_58" src="https://user-images.githubusercontent.com/17761877/181905548-625d794b-2f2b-4e7f-bd50-6d6abca325d3.png">

**Comment by asheerrizvi** [comment] 2022-07-30 13:01
@thisismattia you can see an example over here:

https://bvaughn.github.io/react-virtualized/#/components/Masonry

On mobile it will be a single column. Since we can have variable height cards Masonic layout seems to be the most appropriate imo. Plus, react-virtualized seems to support it out of the box so +1 for that as well. 😆

**Comment by thisismattia** [comment] 2022-07-30 15:43
Oh ok, I see what you mean. Actually that wouldn't the preferred layout. 
Ideally we go for a grid system where each card take up the same height on the page.
Is there a simple way out of the box to achieve that?

**Comment by asheerrizvi** [comment] 2022-07-30 16:03
Sure, think we can do that as well. Will submit a PR. 👍

**Comment by asheerrizvi** [comment] 2022-08-11 07:29
@thisismattia shoot almost forgot about this. Can you assign this to me so that I can track it. Will come up with a PR as soon as I can.

**Comment by asheerrizvi** [comment] 2022-08-14 11:24
@thisismattia was thinking of a solution along the following lines:

1. Make each card be 434px in height. This will have enough space to list all the available tags as well.
2. Clamp the heading to 2 lines. If it is bigger than 2 lines then it will show ellipsis.

This will make it look somewhat like this:

https://user-images.githubusercontent.com/17976252/184534462-6c147d21-df60-4d73-8402-c5bf2f4d38d5.mp4

Let me know if this is a viable solution and I'll open a PR.

Also @thisislawatts we should refactor this component to use a Grid (from React Virtualized) instead of List like it is currently doing.

**Comment by thisismattia** [comment] 2022-08-15 07:14
hey @asheerrizvi thanks for this proposal. Unfortunately I am not sure this would be the best practice for responsiveness and will result in much unnecessary white space.

Wouldn't something like flex:stretch work in this case?
Also grids could work indeed but ideally we stay away from fixed px based sizes. 

Thanks!

**Comment by asheerrizvi** [comment] 2022-08-15 07:19
@thisismattia true. Tell me this though. Lets say we have three cards in a row with auto height. One of them has a height of let's say 500px due to its content. What should happen to the two other cards which are less than 500px? Should they stretch to be 500px? Those two stretched cards will also have white space in that scenario since their content is less.

**Comment by thisismattia** [comment] 2022-08-15 07:26
Yes I would say that's the desired scenario. 

We rarely will have a card that is 500px as we have a char limit on the title so it is really just the pixel difference btw having the title in one line of text or two I think. 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/17761877/184593480-85dfbecf-4bb1-490b-bbea-7c93978371b1.png">

**Comment by asheerrizvi** [comment] 2022-08-20 07:42
Hey guys, I am somewhat stuck on this one. This grid uses `react-virtualized` and is using its `CellMeasurer` component to measure each row. The issue is that `CellMeasurer` is not able to correctly calculate the heights of these rows. For example the height of the first row in the below image should be much more than 403px.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/17976252/185734565-cc696e22-ae2c-4e56-819f-bbf18a17c69b.png">

Another example:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/17976252/185734586-cf2b742e-a69e-4bdf-a77d-258dc794532c.png">

The issue seems to be with `CellMeasurerCache` (particularly the `keyMapper` function) and how we are passing `0` for row and column indexes. But using `index` for `rowIndex` doesn't resolve the issue either. Relevant code is here:

https://github.com/ONEARMY/community-platform/blob/3e61b713f2daaa316ce0a2fa3a1dcac428d5d78f/src/pages/Howto/VirtualizedFlex/VirtualizedFlex.tsx#L28

https://github.com/ONEARMY/community-platform/blob/3e61b713f2daaa316ce0a2fa3a1dcac428d5d78f/src/pages/Howto/VirtualizedFlex/VirtualizedFlex.tsx#L76

Would appreciate if someone can chime in and offer help.

**Comment by thisismattia** [comment] 2022-08-23 15:47
Hey hey thanks for the update. I am not the best person for this. 
Hopefully maintainers find the time to help you on this 🤞

**Comment by asheerrizvi** [comment] 2022-08-24 04:14
Yea I meant the moderators only 😆

**Comment by davehakkens** [comment] 2022-08-25 21:23
Sorry for the slow response @asheerrizvi maintainers are on holiday!

**Comment by asheerrizvi** [comment] 2022-09-25 10:36
I think I have finally found a fix 😄 

https://github.com/ONEARMY/community-platform/pull/1947

**Comment by thisismattia** [comment] 2022-09-25 12:12
You are a persistent guy :) I like it ♡
Thanks for this looks much better!

**Closed** 2022-11-25 15:57 UTC
Labels: Type:Bug🐛, Good first issue
