### ISSUE TITLE
Verified users ⭐️ 

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1123] opened 2021-03-31 19:58 UTC
### Description

We are introducing a new verification program for Precious Plastic. This will add a new layer in the community. It will bring verified accounts. These accounts will be manually (in firebase backend?) selected and get a verified badge. We estimate between 20-30 accounts. This will be shown on the map and their profile. 

### Page related
Will be used in :
https://community.preciousplastic.com/map
https://community.preciousplastic.com/u/precious-plastic

### Icon on Map

<img width="285" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/113202731-09df9f80-9263-11eb-93b9-719aa0b17a40.png">

### Icon in Profile
<img width="579" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/113203273-bf125780-9263-11eb-959c-f8a730899a76.png">

### Temp Icon (final will be community vote)
<img width="50" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/113202845-31366c80-9263-11eb-9e2f-669096760858.png">

**Comment by chrismclarke** [comment] 2021-04-05 09:29
I think probably better to avoid need to manually interact with the database, so that would give two options for ways the admin team can mark a profile as verified:

1. We create a button that only admins can see on a workspace profile to mark as verified (like how how-tos can be approved)
2. We add as a feature to the rough admin panel we have

I'd be happy with either approach, so whatever you think would work better for the team @davehakkens ?

As for the database, not much work should be required, probably just adding a field called either `verified` or perhaps `pp_verified` or any other term (open to suggestions), to distinguish better between accounts that might be considered `verified` because they have confirmed their email vs accounts the PP team view as official/confirmed/verified

**Comment by chrismclarke** [comment] 2021-04-05 17:15
Following discussion, plan is for the more simple option 1 for now (more work on the dashboard later). Open if anyone wants to take the issue on.

**Comment by davehakkens** [comment] 2021-04-14 16:58
You interested in this one @tudi2d, or above your skills?

**Comment by catx23** [comment] 2021-04-27 08:40
Great, 20-30 are known gang fans I suppose ? 

Interesting though to be judged by folks living in van, I guess you explain the 100+ censored users why they are not good enough for the gang.

Censorship, more cultworshipping and discrediting folks who suits you well ;-)

**Comment by catx23** [comment] 2021-04-27 08:41
Great, 20-30 are known gang fans I suppose ?

Interesting though to be judged by folks living in van, I guess you explain the 100+ censored users (https://github.com/plastic-hub/pp-next/blob/master/censored_users.json) why they are not good enough for the gang.

Censorship, more cultworshipping and discrediting folks who suits you well ;-)

**Comment by catx23** [comment] 2021-04-27 09:05
I guess this goes the same way as it happened to some users recently : 'your workshop is not ready for the starterkit', without seeing any picture or the like.

**Comment by davehakkens** [comment] 2021-04-27 14:10
@davidyaha wants to take this one on..

**Comment by davidyaha** [comment] 2021-04-27 14:36
On it :)

**Comment by davidyaha** [comment] 2021-04-28 18:39
@davehakkens 

1. do we have an svg file of the verified icon?
2. I saw [here](https://github.com/ONEARMY/community-platform/blob/master/src/models/user.models.tsx#L28) that the user table already has a verified flag. Should I use that flag to determine whether this icon will be shown on the card?

**Comment by davidyaha** [comment] 2021-04-28 19:23
Just saw this icon: https://github.com/ONEARMY/community-platform/blob/master/src/assets/icons/icon-expert.svg

3. Can anyone with permissions to the dev firebase verify one of the user profiles so I could check that the whole thing work?

**Comment by davehakkens** [comment] 2021-04-28 19:29
hey!
1. You can use that placeholder for now!
2. That's another kind of verification. (for us to approve how-to's and map-pin's) This verification would be done manually
3. Not really. Like mentioned above, we still need to build this new "verificaton field" for profiles

**Comment by davidyaha** [comment] 2021-04-28 19:58
So I might not fully understand 😞 
From what I could see in the code the map pin is an extension of a user profile. meaning the base information is from the user table. Also, the profile page shows information from the user table.

Hence, it would be most effective to have the user's "verification field" on the user table, correct?

Should I just add it next to the existing `verified` field with this name - `verificationBadge`?
Either way, you could manually change those flags on the firebase UI. 

I've created a WIP PR (used the placeholder and existing `verified` flag for now) so you could see what I've done and if that works.

**Comment by davehakkens** [comment] 2021-04-28 20:31
yes indeed, map pins is part of profiles. Some users create a map-pin, we verify them to see if they are legit.
What you are making now is another layer of verification. Both indeed linked to a profile (bit confusing that we call them both verified)

But your suggestion sounds good to me. But @chrismclarke has a better overview on the database. Ok for you Chris?

**Comment by chrismclarke** [comment] 2021-04-29 12:14
> So I might not fully understand 😞
> From what I could see in the code the map pin is an extension of a user profile. meaning the base information is from the user table. Also, the profile page shows information from the user table.
> 
Yep that's right, we use the user profile to generate the map pin (`setUserPin` method called from the `user.store` on profile update). 

> Hence, it would be most effective to have the user's "verification field" on the user table, correct?
I think so, as we will likely want the option to also show it on their profile or other places. 

> Should I just add it next to the existing `verified` field with this name - `verificationBadge`?

I like this option personally, I think 'verified' is a bit too vague (e.g. also having email verification). Another option would be to store a `badges` object in the user profile, in case we might think of more badges we want to assign to a profile in the future (like gamification), and have this one as `badges: {"verified: true"}`

At some point we will want to add to the admin dashboard to make it easier to change these things from inside the platform itself, but until then likely easiest if I just share access to the dev db with you. If you can send me a message either on here, slack, or email (chris.m.clarke@live.co.uk) I can add you.

**Comment by davidyaha** [comment] 2021-05-05 19:24
@chrismclarke 

> I like this option as I think 'verified' is a bit too vague (e.g. also having email verification). Another option would be to store a `badges` object in the user profile, in case we might think of more badges we want to assign to a profile in the future (like gamification), and have this one as the base for a future system, i.e `badges: {"verified": true}` - what do you think @davehakkens?

Just saw this.. atm I've added the said `verifiedBadge` property. I have an issue with seeing changes from firebase on the frontend. Just sent @chrismclarke  an email about it so hopefully, when we resolve that issue I could quickly make the change to `badges` and close that feature.

**Comment by AnneBarbier** [comment] 2021-05-07 06:52
![image](https://user-images.githubusercontent.com/10199681/117409361-f5c43900-aec5-11eb-9c55-966099ea3112.png)

I hope you're aware that this is going to be huge set back for the community and project.

**Comment by chrismclarke** [comment] 2021-05-07 10:20
Cool, @davidyaha - just replied to the email (been a busy week so sorry about the slow response).

**Closed** 2021-05-27 23:36 UTC
Labels: Backend, Frontend, Good first issue, Help wanted
