### ISSUE TITLE
[bug] email link in user profile is broken

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#789] opened 2019-11-21 07:13 UTC
**Describe the bug**
if you click on "email" it opens a page with a broken URL

**To Reproduce**
https://community.preciousplastic.com/u/Atelier%20Lamoureux
click on "email"
see broken page

**Expected behaviour**
I think we want to open a composing email window? using "mailto:"

**Comment by BenGamma** [comment] 2019-11-21 12:26
duplicate of #762

**Closed by BenGamma** 2019-11-21 12:26 UTC
Labels: Priority: High❕, Type:Bug🐛
