### ISSUE TITLE
[feature] Remove Back button

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2774] opened 2023-09-12 23:56 UTC
**Is your feature request related to a problem? Please describe.**
We currently use a back button. But its pointles since browsers have this build in and on mobile you swipe +it takes up important header space.

**Describe the solution you'd like**
Remove the back button 

**Where is the button**
[Single how-to](https://dev.onearmy.world/how-to/test-for-category-filter)
[Single Research](https://dev.onearmy.world/research/testing-new-form)

**Screenshots**
<img width="171" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/4db42ada-d279-4987-96a8-b21dbc3eab83">
<img width="265" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/b4ff5bc1-b65d-4423-b4c8-613a03218899">

**Comment by manuelrurda** [comment] 2023-09-13 05:57
Hi, I'd like to contribute to this project and this issue seems a good way to start. I'm new to Open Source contribuitions but I've follow the contribuiting guide. I'd like to open a Pull Request for this issue but it seems I don't have permissions. 
![image](https://github.com/ONEARMY/community-platform/assets/62727899/32cb135c-4f14-45d1-83b8-8f327cc86bcb)

**Comment by Anish99594** [comment] 2023-09-13 08:27
@davehakkens hi, i have done with the issue, please assign this to me.
Thanks

**Comment by AlfonsoGhislieri** [comment] 2023-09-13 14:25
#2778 gets rid of these, do we want to also keep the bottom one?

![image](https://github.com/ONEARMY/community-platform/assets/652368/0ba39e31-da74-4b14-b865-09f2d2c7b6b3)

**Comment by davehakkens** [comment] 2023-09-13 14:44
I would say that whole footer can be removed. Good moment to think of a better more engaging one

**Comment by AlfonsoGhislieri** [comment] 2023-09-13 14:45
Okay so get fully rid of it for now..?

**Comment by manuelrurda** [comment] 2023-09-13 15:18
> I would say that whole footer can be removed. Good moment to think of a better more engaging one

How does someone get assigned and Issue? I tried to post a PR for this issue yesterday but couldn't

**Comment by AlfonsoGhislieri** [comment] 2023-09-13 15:22
Hi @manuelrurda we no longer assign individuals to specific issues, this avoids an issue becoming blocked up and us having to chase people down - leading to a lot of admin work for a small team of maintainers. 

Posting a PR for the issue is the only real way to get it 'assigned' per say.

**Comment by laviodias** [comment] 2023-09-13 17:12
I believe he was trying to directly open a PR for the main repo and couldn't.
Probably he cloned this repo instead of forking it.

So, if that's the case, @manuelrurda, you should accept that `Fork this repository` option that was shown to you. With that, you'll have a "copy" of the entire project on your github. There you can publish your branches and then open a PR from your fork to this repo.

**Comment by manuelrurda** [comment] 2023-09-13 17:15
Thank you for your answer, then I'll be on the lookout for new opportunities to contribute to this project

**Closed** 2023-09-14 19:43 UTC
Labels: Good first issue
