### ISSUE TITLE
[feature request] Add "other" country and make it mandatory to fill in

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2137] opened 2023-02-28 23:07 UTC
### Description

We want to have more complete user profiles on the platform. We will take a few steps to get there, these are the first two steps.

1. Add a country to the `Your location` dropdown called 'other'. Selecting this shows the (new https://github.com/ONEARMY/community-platform/pull/2135) default country flag in the user profile. Ideally this 'other' is on top of the dropdown list so it wont be missed.
2. Make the `Your location` dropdown mandatory to fill in when completing the user profile, like the rest of the input fields around it.

### Page related

Will be used in :

- [User profile settings](https://dev.onearmy.world/settings)

### Mockup

![afbeelding](https://user-images.githubusercontent.com/13672737/222000502-6c42ed20-c462-4da6-bd17-80b7200ce16c.png)

### Note 1

The `Your location` dropdown goes away when people add themselves on the map. If this is done the location of the map will be used. Make sure to test this behaviour properly that it doesnt conflict with the mandatory dropdown

### Note 2 

This issue is based on a conversations in this issue https://github.com/ONEARMY/community-platform/issues/2134.

**Comment by thisislawatts** [comment] 2023-03-01 20:15
@davehakkens what do you think about making the Location property required when creating an account?  

![Screenshot 2023-03-01 at 21 05 53](https://user-images.githubusercontent.com/472589/222254380-90f1ea9f-3bfd-4836-bb18-1d899ccced31.jpg)

We could then include _Prefer not to say_ as one of the options. 

![Screenshot 2023-03-01 at 21 14 34](https://user-images.githubusercontent.com/472589/222255599-ccf0b783-af47-40de-bd4e-0ad91c90725c.jpg)

**Comment by davehakkens** [comment] 2023-03-01 22:28
nice! I like bringing this information more upfront to get more complete profiles. 
(our audiance usually is also fine to take the extra effort so dont think it would reduce much signups)

However this only solves the country flag, but not incomplete profiles.
So what about taking all member information to the front? 
This would make all members profiles complete and spaces would need fill in additional info


![signup](https://user-images.githubusercontent.com/13672737/222279582-aadea126-4d41-4ee8-8160-36846c36f39d.jpg)

**Comment by noalbalint** [comment] 2023-03-02 10:35
Hi, long time follower of the project, new to the repo, hoping to start contributing soon :) just wanted to add my 2cents (does that expression translate?) to the discussion here

just tested https://github.com/ONEARMY/community-platform/pull/2135 on the preview url, wanted to +1 the above comment ^ as a new user myself, I find it would be nicer to have the whole signup/profile flow in one place/done at the start. I also see in that screenshot the the `links` and `tell us about yourself` fields are no longer mandatory - was that intentional? 

with all that said though, I actually couldn't find that 'forum' view, where the flags would be displayed. where is that?

**Comment by thisismattia** [comment] 2023-03-02 11:46
Yes! This came up a few time in our Community Sprint at Precious Plastic but I am always scared of requesting such (big?) changes to the team. We think this is the best way forward to try get complete profiles on the cp. Happy to clean up the design if needed @davehakkens

**Comment by thisislawatts** [comment] 2023-03-02 17:41
Maybe I have taken this issue off in the wrong direction, I was looking to solve the problem:
_Add "other" country and make it mandatory to fill in_

My understanding here is that the country is high priority because we use this value to display a flag next to a username; shown in How to Credits and next to Comments. 

I worry that introducing too many additional fields during the sign flow will cause people not to complete the sign up process. Consider wWhat is the "conversion" rate at the moment for our signup process? This means how many people start vs. how many complete the sign up process.

Please consider the following two call to actions which will prompt you to login/sign-up.

**Marking as Useful**
![Screenshot 2023-03-02 at 18 24 15](https://user-images.githubusercontent.com/472589/222504976-7c5a8f95-52ac-4bae-92e1-7c31c0cd2456.jpg)

**Leave a Comment**
![Screenshot 2023-03-02 at 18 24 25](https://user-images.githubusercontent.com/472589/222504979-1e6c376a-d055-4306-aa93-24c8bdb8476a.jpg)

This means that before a prospective community member can mark something as useful **or** leave a comment that they **must**:
1. Specify a Display name
2. Location
3. Write a short blurb about themselves
4. Provide contact links
5. Source and upload a photo (they not be using their primary device)

Does this seem like a friendly or delightful first experience when interacting with a new website? Is this a form you would complete to mark something as Useful or leave a comment?

I do agree that incomplete profiles is a problem, but I question whether adding all of these mandatory fields during sign up will harm more than help the community.

**Comment by davehakkens** [comment] 2023-03-03 10:45
> Does this seem like a friendly or delightful first experience when interacting with a new website? Is this a form you would complete to mark something as Useful or leave a comment?

I think this will be inevitable.

We don't want people commenting without completing their profile. (For the flag + to you see who is on the other side of the conversation) So we will make profile completion mandatory before commenting. The completion could be done after signup as a second step, in this case the proposal would be to do it straight away on signup.

Agree for useful it's a bit different since it's less interactive. But still wouldn't hurt to have more complete profiles to see who is behind when someone marked your content as as usefull and you get a notification.

**Comment by thisismattia** [comment] 2023-03-03 11:42
Seems like we have 2 major categories of users:
- Simple members, these are people tagging along that create an account to mark as useful or comment. Indeed requiring them to fill all those fields seems unnecessary burdensome for the task they're trying to achieve. 
- Complete profile, these are recyclers signing up to run their recycling organizations. Indeed from them we would want a complete profile with all infos. 


Picture this @davehakkens : I am follower of Precious Plastic on IG, I see a post about this cool coffee techinque to make bioplastic, I get sent to this new platform, I see the guide, a step is not fully clear to me, I want to comment and ask a thing, I have to make an account to comment, to make the account I have to give a lot of info (and as @thisislawatts says potentially I don't even have an image handy to upload). I might give up and go back to my day. 

Additional question for us: do we care about all those data for a user that just want to comment on something? Potentially yes. Dunno. Would definitely make the platform more friendly than a bunch of incomplete profiles. 

I think by making the signup more complicated we would miss on large number of usefuls and comments.

**Comment by thisislawatts** [comment] 2023-03-03 12:27
Would it be worth listing out the problems caused by an incomplete profile? 

The other challenge I see facing the various platforms is low and falling levels of interaction.

Do you think lack of interaction poses a more significant and existential threat to the Platform mission? If so, does that mean minimising friction between a prospective member and community interaction is higher priority?

**Comment by thisislawatts** [comment] 2023-03-03 17:21
Some interesting discussions here but maybe this issue thread is not the right place for it 😅

I would suggest we either kick-off a separate Discussion to iterate on what fields should be required and where. 

Going back to the original requirement for this Issue which was around making the location field mandatory. Do we want to extend the definition of done for this Issue to include the sign up page? This would prevent new profiles being created without a location declared.

**Comment by noalbalint** [comment] 2023-03-03 19:07
sorry @thisislawatts, going even further off topic here, but just want to strike where the irons hot – are you still doing monthly dev calls? and it looks like the Discord invite link [here](https://github.com/ONEARMY/community-platform/discussions/1854) has expired, would it be possible to send me a new one? :)

**Comment by thisislawatts** [comment] 2023-03-03 19:54
Not a problem @noalbalint ;) I don't think that the monthly developer calls are taking place at the moment. But you're welcome to join the communities Discord. Here's a current link; https://discord.com/invite/gJ7Yyk4. See you in there.

**Comment by davehakkens** [comment] 2023-03-04 00:22
> Some interesting discussions here but maybe this issue thread is not the right place for it 😅
Going back to the original requirement for this Issue which was around making the location field mandatory. Do we want to extend the definition of done for this Issue to include the sign up page? This would prevent new profiles being created without a location declared.

Agree goes a bit beyond the issue. I would wait for adding it on signup page @thisislawatts until we have clear what we want there. So we can add the changes all at once. But it would be good to use the "prefer not to say' instead of 'unknown' like you suggested for the dropdown

Indeed no public calls at the moment @noalbalint. But feel free to take an issue to get started with the codebase :)

**Closed** 2023-06-30 17:08 UTC
Labels: Good first issue
