### ISSUE TITLE
[bug] deleted user still appear on the map

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#772] opened 2019-11-15 12:54 UTC
**Describe the bug**
Deleted users still appears on the map.

**To Reproduce**

1. Check the pin of Precious Plastic Landcaster on the map (see screenshot)
2. Click on user profile
3. See error : user not found

**Expected behavior**
Map pin should be deleted with user.

**Screenshots**
<img width="620" alt="Capture d’écran 2019-11-15 à 13 45 19" src="https://user-images.githubusercontent.com/4993215/68944881-4b2af880-07af-11ea-9ef6-9633f81f7aae.png">

**Comment by davehakkens** [comment] 2019-12-16 02:28
Not sure if this user was actually deleted. Might be a bug since it looks like its back now 
<img width="397" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/70874804-154a8100-1fb4-11ea-9a9c-792e76d514a6.png">

**Comment by Ulian** [comment] 2022-11-21 01:20
I was able to reproduce this issue on localhost. The problem is that when a user is deleted there is nothing that marks the pin as deleted or removes the doc.

I have three questions:
1. The mappin document should be removed or should be updated with `_deleted: true`? I check the user and is deleted by removing the document.
2. Should be removed in `onDelete` hook ([similar to this](https://github.com/ONEARMY/community-platform/blob/master/functions/src/userUpdates/index.ts#L21)) or should be something we call [where the user is deleted](https://github.com/ONEARMY/community-platform/blob/master/src/stores/User/user.store.ts#L269)?
3. Is there something else that should be removed when a user is deleted?

Also, a script must be made to remove all the pins where the user doesn't exist anymore.

I will like to take this one so I can learn some firebase.

**Comment by davehakkens** [comment] 2022-11-21 16:31
Thanks for looking into the old issues. This is still a very useful one the fix! :)
Tagging @chrismclarke in since he would have a better understanding on how to implement this.

**Comment by davehakkens** [comment] 2022-11-27 20:30
Ok whilst waiting for Chris I got an answer on 1 and 2.
1. Lets start with `_deleted: true` for now.
2. ....
3. I asked in our discord.  Like the reply below.
![afbeelding](https://user-images.githubusercontent.com/13672737/204157862-cd663273-2d31-4e10-bde0-2770455b782e.png)
So what can be removed: 
- Profile, email, personal data etc
- Map Pin

What should stay
- How-to's uploaded 
- Research started 
- Comments made

⭐️ Ideally as a bonus we show that the account was deleted. But can imagine this is to much for this issue.

**Comment by chrismclarke** [comment] 2022-12-14 19:39
Sorry this fell off my radar, thanks for weighing in on the discussion @Ulian and @davehakkens 

A couple points from my side

> The` mappin document should be removed or should be updated with _deleted: true? I check the user and is deleted by removing the document.

For now I think this is the best approach. The problem we have is that users keep a cache of old documents in their local indexeddb and so if we simply remove the document there is no way to inform users that it should no longer exist. This isn't an issue for user profiles because they are not cached in the same way (we never need to display all users on a page so don't cache). By marking as `_deleted:true` (and removing all other data from it if wanted) the document still receives an update and so will store in the cache that way. We should then make sure these deleted docs are filtered out from the display

The alternative would be to add an aggregation to summarise all the map pins, and we could use that aggregation to cross-check local indexeddb to delete - however that would be quite a chunk of work and possibly not worth the effort as we're looking into larger changes such as moving towards server-side-rendering which wouldn't use the same indexeddb cache.

> Should be removed in onDelete hook ([similar to this](https://github.com/ONEARMY/community-platform/blob/master/functions/src/userUpdates/index.ts#L21)) or should be something we call [where the user is deleted](https://github.com/ONEARMY/community-platform/blob/master/src/stores/User/user.store.ts#L269)?
Is there something else that should be removed when a user is deleted?

Sounds good to me, I think using hooks to trigger deletions on the backend server is probably more reliable than manually calling from the frontend code. The challenge here is testing those triggers when running locally - this is one of the reasons we have the emulator setup working (not sure if you have used in the past, info in [docs here](https://onearmy.github.io/community-platform/Backend%20Development/firebase-emulators-docker) or let me know if you need any help)

> Also, a script must be made to remove all the pins where the user doesn't exist anymore.

This might have to come as a second stage as I don't think we have great tooling in place to handle migration of legacy data. Although if you did want to test you could look at drafting a firebase function that does the work using a HTTP endpoint or random db trigger, and I can support to get integrated into a wider releases system

**Closed** 2023-07-25 19:10 UTC
Labels: Type:Bug🐛
