### ISSUE TITLE
[bug] Too many unsuccessful login attempts

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#787] opened 2019-11-20 03:33 UTC
**Describe the bug**
"Too many unsuccessful login attempts. Please include reCaptcha verification or try again later" - > just there appears no captcha oO

email: friedrich.kegel@keinefarbe.de

**Comment by BenGamma** [comment] 2019-11-29 00:24
Error messages are not the final ones. For now (beta), we leave them like this because it helps to debug.
Closing because duplicate of #649

**Closed by BenGamma** 2019-11-29 00:24 UTC
Labels: Priority: High❕, Type:Bug🐛
