### ISSUE TITLE
Submit buttons are not enabled after all fields are validated successfully

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#686] opened 2019-10-15 15:52 UTC
**Describe the bug**
This issue happened to many forms: how-to, events. Essentially, the Publish (submit) button was not enabled after the last field was inputted correctly. It required an extra action to fire form validation. The action could be a click, a focus ...
![image](https://user-images.githubusercontent.com/2813016/66848113-ae522100-ef9e-11e9-82c1-d7cff919d3e4.png)

**To Reproduce**
f01e8546d35f8745ef289753cd3b3023fe417ed8

**Expected behavior**
As soon as the last field is entered correctly, the Publish button should be enabled

**Comment by tmhung88** [comment] 2019-10-15 15:56
@chrismclarke logged the issue as discussed

**Comment by chrismclarke** [comment] 2019-10-15 16:02
To the best of my knowledge this only effects the CI, as manual user input triggers validation on click and blur methods. So I think it might just be the testing that needs to update to account for this, because otherwise additional change detection within forms (e.g. every input change event) would be quite heavy

**Comment by chrismclarke** [comment] 2019-10-15 16:02
But maybe someone can test if this also reproduces using manual input

**Comment by BenGamma** [comment] 2019-11-15 15:36
fixed with #745

**Closed by BenGamma** 2019-11-15 15:36 UTC
Labels: Priority: Medium, Type:Bug🐛
