### ISSUE TITLE
[feature request] When opening a research item for the first time, display "Save as Draft" instead of "Revert as Draft

### ISSUE THREAD

**Issue by bagiyal** [ONEARMY/community-platform#2615] opened 2023-07-13 19:30 UTC
**Is your feature request related to a problem? Please describe.**
The current behavior of displaying "Revert as Draft" when opening a research item for the first time can be confusing for users. It would be more intuitive to show "Save as Draft".

**Describe the solution you'd like**
I would like the system to display "Save as Draft" when someone opens a research item for the first time. This change will provide a clearer and more understandable label for users, indicating that they are saving the item as a draft.

![Screenshot (137)](https://github.com/ONEARMY/community-platform/assets/63339447/18485b97-4420-4850-83e9-57cb32101751)

**Comment by thisislawatts** [comment] 2023-07-13 19:37
Duplicate of https://github.com/ONEARMY/community-platform/issues/2508

**Closed by thisislawatts** 2023-07-13 19:37 UTC
