### ISSUE TITLE
[bug] - Settings page cannot save workspace

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#729] opened 2019-10-30 19:38 UTC
**Describe the bug**
I filled out all form fields but save button disabled

**To Reproduce**
Go to settings page, fill out all fields as workspace

**Expected behavior**
Button enabled for save or some sort of warning/error message to identify if something wrong or missing

**Screenshots**
![image](https://user-images.githubusercontent.com/10515065/67892491-0dbd3e80-fb12-11e9-9366-d47d92abe447.png)

**Comment by BenGamma** [comment] 2019-10-31 11:36
I'm not able to reproduce using Firefox & chrome, can you give me more infos ?

But overall I agree that we should allow the click on the save button all the time and only display the errors/required field on click.

**Comment by chrismclarke** [comment] 2019-11-01 19:20
Really strange then, maybe it's linked to my profile being old and conflict with something else somewhere... can try with fresh profile via cypress test. So just to confirm you can create a workspace profile fine? On the dev site there doesn't appear to be anyone with workspace profiles so more difficult for testing the map.

**Comment by BenGamma** [comment] 2019-11-07 10:49
fixed with #747

**Closed by BenGamma** 2019-11-07 10:49 UTC
Labels: Mod: Profiles 👱, Priority: High❕, Type:Bug🐛
