### ISSUE TITLE
Add view count to How-to and Research

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1618] opened 2022-04-25 18:33 UTC
### Description

We want to have a view count on our How-to and Research pages. 

### Page related
[Research](https://community.projectkamp.com/research/can-we-make-an-elevation-height-map-of-the-land#update_3) and [How-to](https://community.preciousplastic.com/how-to/beads-mould---a-lot-of-them) pages. 

### Build suggestion
- It will be build using the aggregations.
- Ideally there is some sort of logic that only counts one visit per **hour**. (To prevent it being mis-used by refreshing 200 times in a row)
- Should be released for `beta-testers` first. So we can test it 

### Mockup

![Views How-to](https://user-images.githubusercontent.com/13672737/165151808-8dd334de-1cd5-4cab-9dd2-892c67e180c8.jpg)
![Views research](https://user-images.githubusercontent.com/13672737/165151817-da9b567f-a9fd-42c3-b88c-58fb33f8569e.jpg)

### Icon 
[download](https://drive.google.com/file/d/1Ljyg74WFQTAxffaQBpr3Kb7ci443kaht/view?usp=sharing)

**Comment by davehakkens** [comment] 2022-04-25 20:00
Want to take on another issue @amandaqiu1 or @ryanwbass? 👆

**Comment by ryanwbass** [comment] 2022-04-26 00:47
Hey @davehakkens  I will take it! Go ahead and assign.

**Comment by davehakkens** [comment] 2022-04-26 07:16
sweet!

**Comment by chrismclarke** [comment] 2022-04-26 08:28
@ryanwbass 
Thanks for taking this on. There might be a bit of added challenge with this one with the best place to actually store this information. The natural place to think would be the howto itself, adding a `viewCount` property and just increasing by 1 any time the howto page is loaded except this will mean howto docs are constantly updated and the entire doc will need to be synced across all users many times (which is a costly set of db read operations)

There's also the not-unlikely scenario that a howto could be viewed by multiple users at similar times, meaning that any client-side updates could easily become out of sync (e.g. two users both increment the count from 2->3 before having the chance to sync the others' update).

So I think I'd recommend a few things:

1. Use a new collection for tracking raw stats. E.g. add a `howto_stats` or similar endpoint to `shared\db.ts` that will hold the viewCount for each doc.

2. Feel free to make a first pass implementing everything with client-side UI and logic (e.g. the button, the logic to increment the viewcount and limit spamming etc.). I wouldn't worry to much about being clever with the spamming code, if someone is determined they will always find a way around so I expect something like a localstorage entry should be fine to at least prevent repeated refresh. If we ever want more accurate stats we can use google analytics that tracks things like IPs for anti-spam

3. Consider moving the increment code to a firebase function which can use special field-value increment functions instead of relying on manual calculation (I can help with this)

4. Consider adding an aggregation to collate all viewcount stats into a single doc for easier consumption in the frontend. I can help with this (we have a pending pr to make backend dev a bit easier using docker emulators instead of firebase server)

**Comment by davehakkens** [comment] 2022-05-18 13:30
hi @ryanwbass are you still planning to take this on?
If not possible, or no time due to moving no worries. 
Just let me know so I can assign someone else

**Comment by ryanwbass** [comment] 2022-05-18 13:47
> hi @ryanwbass are you still planning to take this on? If not possible, or no time due to moving no worries. Just let me know so I can assign someone else

Hey @davehakkens ya I was just thinking the same thing. Between moving, some sustainability projects at home (gardening, etc...), and other development projects Im not finding myself with a lot of time right now. You can assign this one on to someone else. I was super excited to get involved but just have too much going on right now, I haven't had any down time for a few weeks. I will keep the project in mind though and when I find time will be sure to get involved again.

**Comment by davehakkens** [comment] 2022-05-18 15:35
Thanks for the update! Do come back when you find some time @ryanwbass! :)
For now @adrianduke will take over the issue. But for some reason I can't assign.. 🤔

<img width="323" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/169082855-1d181903-1475-4bf7-b514-d3e274168584.png">

**Comment by davehakkens** [comment] 2022-06-16 10:40
awesome!

**Comment by AlfonsoGhislieri** [comment] 2022-06-16 10:55
Just one thing for the implementation, do we want to update the views just when a howto is clicked (this would be definitely the easier choice)? Or also when someone also visits the specific url / refreshes the page?

**Comment by adrianduke** [comment] 2022-06-16 11:27
@AlfonsoGhislieri fyi I came across: https://firebase.google.com/products/extensions/firebase-firestore-counter - might help you along.

**Comment by AlfonsoGhislieri** [comment] 2022-06-16 20:49
@chrismclarke My thinking was to use logic similar to the one I created for the download counter and implement the cool-down in local storage just like I did for the other ticket. I was thinking of extracting some of those functions and making them work for this feature as well.

My main question for implementation really is if we want views to increment only when a user clicks the howto and it loads the page, or also in case of them loading the page via url or refresh. Say someone were to favourite the page and visit it frequently this wouldn’t reflect the total views accurately.  I think handling it onclick would obviously be a lot easier though..

**Comment by chrismclarke** [comment] 2022-06-16 21:05
Oh, that was you also! Amazing, yeah looks like a sensible approach to me.
I think it's ok if things aren't 100% accurate, we also have tools like google-analytics integrated that track individual page views and have more intelligent detection methods for new vs returning visitors etc. I think this is mostly just to give a rough impression and some nice feedback for the creators.

So you can probably just bind to the `componentDidMount` method for the howto page, or even just add on to the existing methods we have for google analytics (search the codebase for `ReactGA`). If there were ways to help make things more generalised and usable for multiple pages that would definitely be a bonus.

**Comment by thisislawatts** [comment] 2022-06-18 08:36
🐒⚡Chaos Monkey Mode(TM)

What we are talking about here is analytics. This is a solved problem and I would argue our own implementation is unlikely to contribute significantly towards the core mission of our software, building sustainable communities around tackling environmental challenges. 

I want to share a few more questions here which I believe are useful in thinking about the implementation. 

- Would the additional complexity this feature introduces impact our ability to deliver on the capabilities that support community growth? 
- Is there already tooling in place that gathers page view data for our application? _Yes! This is Google Analytics. _
- Can we query the gathered data using a page URL to get all page views? 
- What requirements do we have on the accuracy and timeliness of this data?

Some wider context here, we have been looking for an opportunity to spend some time reviewing our analytics tooling. Maybe there is an alternative provider that - would be better placed to meet this new requirement.

**Comment by davehakkens** [comment] 2022-06-18 13:31
Hey thanks all for flagging some issues.

The main reason for implementing this is to show better to the content creators that their contributions are seen and used.
Since we are not aiming to get active comments beyond practical things. And "useful button" will take a while before intergrated into peoples behaviour. Views should be an easy way to bring some of that..

That said:
- Views should also be included from direct url, since many people access them like that.
- This issue was made under the impression that it would be easy to intergrate this with aggregations. It doesn't sound like it is sorry for that.
- Not to keen on intergrating it with Google Analytics since we want to drop that tool. Ideally we dont have to use an additional thirth party (complex to manage with different instances). But if we do I would wait and intergrate them until we switch to provider like for instance [Plausible](https://plausible.io/). However we are not really ready yet to switch and if we do it might be good to intergrate the tool fully to get more potential out of it. (more platform stats)

Overal its not a very urgent feature to intergrate, perhaps better to pause and make sure we have things more clear and are ready to fully open up the analytics box?

**Comment by thisislawatts** [comment] 2022-06-18 18:48
> implementing this is to show better to the content creators that their contributions are seen and used.

I had not considered this use case. That definitely increases the value of this functionality sitting within the platform. I wonder whether a "view" provides enough data to determine whether it has collaborative value. As a metric it could be simply gamed through click bait content.

Is there an opportunity here for the platform to take a stance and only place value and celebrate actual collaborative actions? Such as marking something useful, commenting or remixing someone's idea and building off of it.

**Comment by chrismclarke** [comment] 2022-06-18 19:58
I think there's some good long term thoughts and discussion points here. My main takeaway is that at least short term 3rd party tooling/integration probably doesn't make sense until after we resolve the bigger picture.

So given the question of whether to code a small feature ourselves or not have it at all, I would be voting in favour of adding it I'd hope creators feel it would add value, could be checked in a quick discord poll or similar. I'd also think most of the technical parts are already there with the downloader counter implementation and the existing page view tracking - yes people could still _game_ the system if they wanted, but I'd suggest we make that an issue when it becomes an issue (right now I don't think we've put in any real incentive mechanisms to do so).

**Comment by thisislawatts** [comment] 2022-06-19 07:14
I think if we have a shared understanding of what would success look like for this feature we can build it. It is after all cheaper to not build something then build it and remove it. 

In addition to qualitative feedback from creators is there something we can measure to verify that this feature is providing the desired benefit? 

For example:
- Users who contribute multiple posts have a higher per page view rate than those with a single contribution. 
- Contributors who see a higher view rate for their posts will be more to contribute additional items.
- There are more contributions around certain topics if these generate more views.

**Comment by thisislawatts** [comment] 2022-12-13 08:03
@davehakkens one piece of feedback on the style of this component. **👁️ Views** looks very similar to the **Back** and **Useful** elements which are both interactive and clickable. I think that it would be useful for non-interactive elements to be styled differently to avoid confusing the user. 

![Screenshot 2022-12-13 at 09 03 38](https://user-images.githubusercontent.com/472589/207259803-0657aec2-655a-436d-acbc-5158aa1c5305.jpg)

**Comment by davehakkens** [comment] 2022-12-14 21:56
hey @AlfonsoGhislieri, we had some discussion about this and decided to put this back in.
Would you still be interested to work on it? :)

**Comment by AlfonsoGhislieri** [comment] 2022-12-15 16:22
Hi @davehakkens would love to work on this issue but I’m not sure I’ll have much time on my hands until the new year!

**Comment by davehakkens** [comment] 2022-12-15 16:27
Great. But no Rush. Perhaps you take it on and we check in again mid January? 
Then i'll also update the design that takes the above comment of @thisislawatts into account.

**Comment by davehakkens** [comment] 2023-01-03 11:20
hey @AlfonsoGhislieri happy new year :)
Still needed to follow up here on the design. For now you can use [this component](https://onearmy.github.io/community-platform/storybook-static/index.html?path=/story/components-elwithbeforeicon--default) to keep it simple. We will release the view-count for `beta-testers` only in the beginning so we can gather some views and keep an eye on it.

Let me know if you need anything else to get started

**Comment by AlfonsoGhislieri** [comment] 2023-01-03 14:43
Hi @davehakkens thanks and to you as well!

I actually started thinking about the implementation the other day and was wondering what approach we should take with this.

- Similar to the download counter: once you view a page you get a cooldown and new clicks/refreshes won't count it for however long we set the cooldown to.
- Add a timer, so after you've been on the page for a certain amount of time it will count as a view (eg 1min)
- The final way I thought of is linking the timer to the amount of text present/the duration of a view. This would make it the most adaptive but probably uncessarily complicated.

I quite like the idea of the timer personally, and think that it isn't too complicated to implement. But I defer to your judgment or any input from @thisislawatts or @chrismclarke.

**Comment by davehakkens** [comment] 2023-01-03 17:53
Nice timer sounds nice to me. 
Also makes it very clear what we count as a view. (since every tool does that different metric anyway)
But i'm technically not the best person to judge..

**Comment by chrismclarke** [comment] 2023-01-04 22:09
I think any more complicated rate-limiting logic is handled much better (and harder to spoof) on the backend, so how about just as a simpler short-term solution we just use sessionStorage on the browser?

https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage 

So when you view a page it first checks if there's already some `page_view_pagename` variable saved, if no trigger the view count updater and add it, if yes ignore. The storage will then get cleared next time the user closes all tabs with the site open, and revisits

As for the code that is triggered to increment the counter, I can't remember how exactly the download or useful counters work but could be worth an initial try and can always refactor later if needed. 

Otherwise could maybe try storing first within the users own profile their own individual view counters, and then using the aggregations system to update a global copy for all users (like we do with useful votes)?

**Comment by AlfonsoGhislieri** [comment] 2023-01-05 20:16
@chrismclarke yeah that makes sense, somewhat similar to what I did for the download counter!

I’ll use the logic similar to the download counter and tie it all together with session storage then! :)

**Comment by AlfonsoGhislieri** [comment] 2023-01-20 10:16
Quick update, ran into a little blocker which kept me stuck a little while, but seem to have it all sorted now. Hoping to finish by next week :-)

**Comment by davehakkens** [comment] 2023-01-20 12:23
thanks for the update!

**Comment by AlfonsoGhislieri** [comment] 2023-01-20 21:37
@chrismclarke @thisislawatts 

I'm running into a little issue when updating the view count on the backend. I can't figure out how to run an update on a specific dbRef (seems that I can can only set, and even when setting the option to merge this in an error). The issue is that by just using .set the `_modified` field is being changed everytime a view is added, and I can't override this by passing the correct _modified field to the backend.. 

The code should be pretty simple but I'm not sure why I can't get it to work, these are the lines I tried to use:

`dbRef.update({
      total_views: totalViews + 1
    })`

or 

`dbRef.set({ total_views: totalViews + 1 }, { merge: true });
`

**Comment by chrismclarke** [comment] 2023-01-23 01:58
Hey @AlfonsoGhislieri 

By default any db updates called from the frontend go via an intermediate layer which updates timestamp, so I think if you want to avoid that we could update the code in [src/stores/databaseV2/DocReference.tsx](https://github.com/ONEARMY/community-platform/blob/master/src/stores/databaseV2/DocReference.tsx#L93-L94) to allow retaining the `_modified` timestamp, although to avoid potential knock-ons we might need to allow passing the setting as an option to all db.set commands, e.g.
```
async set(data: T, options:{keep_modified_timestamp:boolean})
```
Alternatively we could create a backend function that handles the actual increment. You could create the function via the `functions.https.onCall` method, and that will expose in the frontend via ` functions.httpsCallable(fnName)`
You can see an example of this pattern if you search for the `getUserEmail` function.

Feel free if you want to open a draft PR to troubleshoot any further

**Comment by AlfonsoGhislieri** [comment] 2023-01-23 14:37
Thanks a lot for this @chrismclarke, I'll have a look and implement one of these during the week and open a draft PR!

**Comment by chrismclarke** [comment] 2023-01-23 18:10
Sounds great, if you do go down the backend functions route, you might also be interested to know firebase provides a special `FieldValue.increment` function that can be used to automatically add a specified amount to a target document fields (so less risk of sequential updates getting 'lost' if both are triggered around the same time and try to set as the same fixed value)

https://cloud.google.com/firestore/docs/samples/firestore-data-set-numeric-increment 

If we ever did need a more precise/resilient counter firebase does have support for distributed counters (multiple fields to update and then aggregate together), however I think that would be definite overkill for this type of feature/anticipated update frequency

**Comment by AlfonsoGhislieri** [comment] 2023-01-26 12:34
So I've spent a little while trying to get these backend functions to be able to use the update function, but I can't for the life of me figure it out. 

After I grab the dbRef using:
`const dbRef = this.db.collection<IResearchDB>(COLLECTION_NAME).doc(id)`

I only have the following commands that I can run on it: `batchDoc`, `delete`, `get`, `id`, `set` and `stream`. There seem to be a lot of firebase commands missing... I'm not sure if this has been limited elsewhere in the codebase?

Maybe you have some ideas? Or else it might be easier to just retain the modified timestamp like you suggested earlier.

**Closed** 2023-02-21 04:44 UTC
Labels: ⏳Under discussion, Bounty Level 2
