### ISSUE TITLE
Flag mandatory 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2134] opened 2023-02-27 01:10 UTC
Would it be possible to make the country field aka flag on the user settings mandatory?
Having users without it makes it look buggy and more boring 😎

<img width="883" alt="Screenshot_2023-02-26_at_20_08_01" src="https://user-images.githubusercontent.com/17761877/221449883-5e84ccd0-20f5-4e37-b1d6-587d67a9f96f.png">

<img width="1165" alt="Screenshot_2023-02-26_at_20_10_25" src="https://user-images.githubusercontent.com/17761877/221450075-b2d31a10-a4a0-49e8-8122-7850d2068d8a.png">

**Comment by thisislawatts** [comment] 2023-02-27 12:06
That's odd. I think that without a flag the Username should fall back to a default One Army flag. But that is maybe imagined behaviour rather than what has been coded.

I feel that making country information mandatory is the wrong direction here. I am speaking as someone with a bias against using flags as a shorthand for identity.

**Comment by thisismattia** [comment] 2023-02-27 16:35
Oh, I think i've heard that before but I personally never seen oa icon next to usernames

Ok, don't have any big opinion regarding flags.. just make the website a bit more fun imo

**Comment by thisislawatts** [comment] 2023-02-27 18:17
I will raise a PR shortly for this. It seems a  straightforward change to make

**Comment by davehakkens** [comment] 2023-02-27 22:03
I think you raise the issue because you want to see diversity and completed user profiles.

We can make the country flag field mandatory or add a placeholder flag. 
But I don't think it solves the problem.

The problem is not that people skip the `country` field but that people don't complete their profile. 
They simply skip that entire step. (like in your [example](https://community.preciousplastic.com/u/elitsa) above, no info is added)
Because completing profiles is ****not mandatory** atm.**


This PR (https://github.com/ONEARMY/community-platform/issues/1588) and this PR (https://github.com/ONEARMY/community-platform/pull/1868) where a start make profile completions more clear for users: 
But seems we might need to take it to the next step since there are still many profiles incomplete.

Which is **make it mandatory** to complete the profile before posting.
But I see a few things that need to happen before

1. Add a new country location in the dropdown for users that don't want to show their country flag.
2. Make country location dropdown mandatory
3. Do a few deep tests to make sure the completing of profiles is complety bug free on multiple browsers and devices
4. Make the completion of profiles mandatory before posting.

**Comment by thisislawatts** [comment] 2023-02-28 18:48
Do we have any feedback to community members as to **why** they are not completing their profiles?

**Comment by davehakkens** [comment] 2023-02-28 22:24
> Do we have any feedback to community members as to **why** they are not completing their profiles?

No not that I'm aware. Every know and then we do get some profile bugs but nothing that should stop from completion.
This was also one of the reason to start that Discord channel, to get more website feedback. Trying to create an easier place to drop an issue.

**Comment by davehakkens** [comment] 2023-02-28 23:09
I broke this issue in a new, more actionable issue here: https://github.com/ONEARMY/community-platform/issues/2137
Feel free to continue the conversation. But closing for now so it doesn't confuse new contributors.

**Closed by davehakkens** 2023-02-28 23:09 UTC
Labels: Type:Bug🐛
