### ISSUE TITLE
Editing an existing how-to inserts a new document

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#700] opened 2019-10-17 12:03 UTC
**Describe the bug**
Right after an user submitted edit changes, a new document was created and the original document stayed intact in the collection

**To Reproduce**
Run the **[Edit a how-to]** test in this #689 and notice a new document is inserted after the edit is done.

**Expected behavior**
All changes should be updated against the existing document. No new document should be inserted

**Comment by BenGamma** [comment] 2019-10-29 20:07
Is it fixed ? I can't reproduced from `master` and it's not present in the bug.spec.ts file. @tmhung88 ?

**Comment by tmhung88** [comment] 2019-10-30 13:04
@BenGamma it's still there. You can check by looking at firestore db of **onearmy-test-ci**. This is the inserted record on edit

![image](https://user-images.githubusercontent.com/2813016/67860470-7deab500-fb50-11e9-9c1b-7bf1843f7027.png)

**Comment by chrismclarke** [comment] 2020-04-15 21:46
appears to be working, closing

**Closed by chrismclarke** 2020-04-15 21:46 UTC
Labels: Priority: Urgent❕❕❕, Type:Bug🐛
